#!/bin/bash
sudo apt-get update
sudo apt-get install docker-engine -y
sudo service docker-start
docker login abc
echo "$DOCKER_HUB_PWD" | docker login --username="$DOCKER_HUB_UNAME" --password-stdin
docker pull abc/image:latest
docker tag abc/abc:latest xyz/example/aquasecurity-repo/cybercenter:latest
docker logout abc
docker login xyz
echo "$DOCKER_HUB_PWD" | docker login --username="$DOCKER_HUB_UNAME" --password-stdin
docker push xyz/example/aquasecurity-repo/cybercenter:latest


$ echo "secret" > /root/configs/password.txt
